/* Shared theme tokens + demo data for the Event Reservation module. */
export const EC = {
  green: "#16A34A",
  greenLight: "#DCFCE7",
  blue: "#2563EB",
  blueLight: "#DBEAFE",
  orange: "#F59E0B",
  orangeLight: "#FEF3C7",
  pink: "#DB2777",
  pinkLight: "#FCE7F3",
  red: "#EF4444",
  redLight: "#FEE2E2",
  slate: "#0F5C7A",
};

export const HALLS = ["Kyoto Hall", "Nyoto Hall", "Beshiro Hall", "Ushiba Hall", "VIP Room"];
export const FUNCTION_TYPES = ["Wedding", "Family Gathering", "Corporate Meeting", "Birthday Party", "Conference", "Seminar"];
export const BOOKING_STATUS = ["Confirmed", "Tentative", "Cancelled"];
export const PAYMENT_MODES = ["Cash", "Card", "QR / e-Money", "Bank Transfer", "Credit"];
export const SALES_EXECUTIVES = ["Annam Names", "Dorner Namer", "Aannia Lata", "Yant Nepely"];
export const OUTLETS = ["IRVEK Restaurant — Higashiomi, Shiga", "IRVEK Banquet — Kyoto"];

let seq = 3;
export const nextReservationNo = () => `RSV-${String(2638820 + seq++).slice(0, 7)}`;

export const EVENT_RESERVATIONS = [
  {
    id: "EV-0000001",
    reservationNo: "2638823",
    eventFrom: "2026-06-26",
    eventTo: "2026-06-26",
    hall: "Kyoto Hall",
    halls: 1,
    company: "Family Gathering",
    guest: "Ranjan Neupane",
    contact: "872336224",
    email: "ranjan@example.com",
    functionType: "Family Gathering",
    salesExecutive: "Annam Names",
    status: "Confirmed",
    pax: 50,
    guaranteedPax: 55,
    ratePerPax: 3000,
    hallCharge: 3000,
    totalCharge: 230000,
    totalBilled: 0,
    advance: 20000,
    paymentMode: "Bank Transfer",
    startTime: "11:00",
    endTime: "15:00",
    notes: "Vegetarian menu for 12 guests.",
  },
  {
    id: "EV-0000002",
    reservationNo: "2638824",
    eventFrom: "2026-06-26",
    eventTo: "2026-06-26",
    hall: "Beshiro Hall",
    halls: 1,
    company: "Confinay Party",
    guest: "Sandesh Manandhar",
    contact: "9902343785",
    email: "sandesh@example.com",
    functionType: "Corporate Meeting",
    salesExecutive: "Dorner Namer",
    status: "Confirmed",
    pax: 40,
    guaranteedPax: 40,
    ratePerPax: 2500,
    hallCharge: 2000,
    totalCharge: 150000,
    totalBilled: 0,
    advance: 10000,
    paymentMode: "Card",
    startTime: "18:00",
    endTime: "21:00",
    notes: "",
  },
  {
    id: "EV-0000003",
    reservationNo: "2638825",
    eventFrom: "2026-07-04",
    eventTo: "2026-07-04",
    hall: "VIP Room",
    halls: 1,
    company: "Sato Events Co.",
    guest: "Sato Wedding Party",
    contact: "805512347",
    email: "sato@events.jp",
    functionType: "Wedding",
    salesExecutive: "Aannia Lata",
    status: "Tentative",
    pax: 120,
    guaranteedPax: 100,
    ratePerPax: 4200,
    hallCharge: 50000,
    totalCharge: 554000,
    totalBilled: 120000,
    advance: 100000,
    paymentMode: "Bank Transfer",
    startTime: "12:00",
    endTime: "17:00",
    notes: "Stage + live band setup required.",
  },
];

export const emptyReservation = () => ({
  id: "",
  reservationNo: nextReservationNo(),
  eventFrom: "",
  eventTo: "",
  hall: HALLS[0],
  halls: 1,
  company: "",
  guest: "",
  contact: "",
  email: "",
  functionType: FUNCTION_TYPES[0],
  salesExecutive: SALES_EXECUTIVES[0],
  status: "Tentative",
  pax: 0,
  guaranteedPax: 0,
  ratePerPax: 0,
  hallCharge: 0,
  totalCharge: 0,
  totalBilled: 0,
  advance: 0,
  paymentMode: PAYMENT_MODES[0],
  startTime: "",
  endTime: "",
  notes: "",
});

export const money = (n) => `¥${Number(n || 0).toLocaleString()}`;
