/* ------------------------------------------------------------------
   Japanese dictionary for the POS UI.
   Keys are the English strings rendered anywhere in the app; the
   translation layer in PosApp.jsx matches them case-insensitively and
   tolerates trailing punctuation (":", "…", "...", "*").
------------------------------------------------------------------- */
export const JA_DICT = {
  /* ---------------- Navigation & shell ---------------- */
  "Dashboard": "ダッシュボード",
  "Self Service / Fastfood": "セルフサービス／ファストフード",
  "Take Order": "注文取得",
  "Tables": "テーブル",
  "Table List": "テーブル一覧",
  "Orders": "注文",
  "Order": "注文",
  "Settlement": "精算",
  "Customers": "顧客",
  "Customer": "顧客",
  "Inventory": "在庫",
  "Reports": "レポート",
  "Kitchen Display": "キッチンディスプレイ",
  "Exit Kitchen Display": "キッチンディスプレイを終了",
  "Promotions": "プロモーション",
  "Employees": "従業員",
  "Employee": "従業員",
  "Shift Management": "シフト管理",
  "Bill RePrint": "伝票再印刷",
  "Settings": "設定",
  "Home": "ホーム",
  "Shift": "シフト",
  "More": "その他",
  "Others": "その他",
  "Takeaway Order": "テイクアウト注文",
  "Delivery Order": "デリバリー注文",
  "Delivery Orders": "デリバリー注文",
  "Event Order": "イベント注文",
  "Event Orders": "イベント注文",
  "New Event Order": "新規イベント注文",
  "Store Request": "店舗申請",
  "Store Requests": "店舗申請",
  "View Store Requests": "店舗申請を見る",
  "Bill Settlement": "会計精算",
  "Customer Ordering": "お客様注文",
  "Setup & Customer Ordering": "設定とお客様注文",
  "Switch Screen": "画面切替",
  "Switch to Custom Layout": "カスタムレイアウトに切替",
  "Open menu": "メニューを開く",
  "Logout": "ログアウト",
  "Terminal": "端末",
  "POS": "POS",
  "POS - Billing": "POS - 会計",
  "POS - Bill Settlement": "POS - 会計精算",

  /* ---------------- Top bar ---------------- */
  "All Outlets": "全店舗",
  "Outlet": "店舗",
  "Outlet Name": "店舗名",
  "Outlet Open": "営業中",
  "Outlet Not Open": "店舗未開店",
  "Online": "オンライン",
  "Admin": "管理者",
  "ADMIN": "管理者",
  "ADMINISTRATOR": "管理者",
  "Manager": "マネージャー",
  "Manager Override": "マネージャー承認",
  "Main Outlet": "本店",
  "Language": "言語",
  "English": "English",
  "Japanese": "日本語",
  "Cashier": "レジ担当",
  "Cashier:": "レジ担当:",
  "Shift:": "シフト:",
  "Staff": "スタッフ",
  "Staff Account": "スタッフアカウント",
  "Logged-in user": "ログイン中のユーザー",
  "Sync": "同期",
  "Refresh": "更新",

  /* ---------------- Notifications ---------------- */
  "Order Notifications": "注文通知",
  "Order notifications": "注文通知",
  "Sound On": "音オン",
  "Sound Off": "音オフ",
  "Clear": "クリア",
  "No order activity yet. Add an item or close an order.": "注文の動きはまだありません。商品を追加するか注文を締めてください。",
  "Added to the running order": "進行中の注文に追加しました",
  "Bill settled": "会計済み",
  "Order sent to kitchen": "注文をキッチンに送信しました",
  "Order saved": "注文を保存しました",
  "Order put on hold": "注文を保留しました",
  "Just now": "たった今",
  "New settlement": "新規精算",

  /* ---------------- Dashboard ---------------- */
  "Quick Actions": "クイック操作",
  "Quick add new item": "商品をクイック追加",
  "Today's Business": "本日の売上",
  "Restaurant Status": "店舗ステータス",
  "Sales Overview": "売上概況",
  "Sales Summary": "売上サマリー",
  "Sales": "売上",
  "Sales (Cash)": "売上（現金）",
  "Top 5 Selling Items": "売上トップ5商品",
  "Alerts": "アラート",
  "Recent Activity": "最近の活動",
  "View All": "すべて表示",
  "View More": "もっと見る",
  "View": "表示",
  "From Main Outlet": "本店より",
  "Today": "今日",
  "Yesterday": "昨日",
  "This Week": "今週",
  "This Month": "今月",
  "Last 7 Days": "過去7日間",
  "Last 30 Days": "過去30日間",
  "Custom Range": "期間指定",
  "Create new order": "新規注文を作成",
  "Settle order": "注文を精算",
  "Settle bill": "会計する",
  "No table assigned": "テーブル未割当",
  "Live kitchen tickets": "キッチン伝票（リアルタイム）",
  "Stock overview": "在庫概要",
  "Table overview": "テーブル概要",
  "Banquets & functions": "宴会・催事",
  "Total Sales": "総売上",
  "Total Orders": "総注文数",
  "Total Customers": "総顧客数",
  "Total Billed": "請求合計",
  "Average Order Value": "平均客単価",
  "Covers": "客数",
  "APC": "客単価",
  "Available Tables": "空きテーブル",
  "Occupied Tables": "使用中テーブル",
  "Running Orders": "進行中の注文",
  "Invoices Generated": "発行済み請求書",
  "Reserved Tables": "予約テーブル",
  "Pending Settlement": "未精算",
  "Pending Orders": "保留中の注文",
  "Pending Only": "未処理のみ",
  "Low Stock": "在庫不足",
  "Kitchen Delay": "キッチン遅延",
  "Shift Not Closed": "シフト未締め",
  "Employees Clocked In": "出勤中の従業員",
  "Anonymous Customers": "匿名のお客様",
  "Anonymous": "匿名",
  "Selected Customers": "選択された顧客",
  "Customer Groups": "顧客グループ",
  "Vacant Tables": "空きテーブル",
  "Net Sales": "純売上",
  "Card Sales": "カード売上",
  "Cash Sales": "現金売上",
  "Cash sales": "現金売上",
  "Payment Method Breakdown": "支払方法別内訳",
  "Tickets": "伝票",
  "All tickets completed": "すべての伝票が完了しました",

  /* ---------------- Common actions & status ---------------- */
  "Add": "追加",
  "ADD": "追加",
  "Add Item": "商品を追加",
  "Add Items": "商品を追加",
  "Add to Cart": "カートに追加",
  "Add Split": "分割を追加",
  "Add Rule": "ルールを追加",
  "Add Reward": "特典を追加",
  "Edit": "編集",
  "Delete": "削除",
  "Update": "更新",
  "UPDATE": "更新",
  "Updated": "更新",
  "Updated By": "更新者",
  "Updated On": "更新日",
  "Created By": "作成者",
  "Created On": "作成日",
  "Save": "保存",
  "Saved": "保存済み",
  "Save Changes": "変更を保存",
  "Save Reservation": "予約を保存",
  "Save & Take Order": "保存して注文へ",
  "Cancel": "キャンセル",
  "Cancelled": "キャンセル済み",
  "Close": "閉じる",
  "Close cart": "カートを閉じる",
  "Confirm": "確定",
  "Confirmed": "確定済み",
  "Continue": "続ける",
  "Next": "次へ",
  "Prev": "前へ",
  "Back": "戻る",
  "BACK": "戻る",
  "BACK TO ORDER": "注文に戻る",
  "Exit": "終了",
  "Apply": "適用",
  "Apply & Continue": "適用して続行",
  "APPLY VALUE": "値を適用",
  "Skip": "スキップ",
  "Skip Discount": "割引をスキップ",
  "Reset": "リセット",
  "Export": "エクスポート",
  "Export Excel": "Excel出力",
  "Export PDF": "PDF出力",
  "Export to Excel": "Excelに出力",
  "Print": "印刷",
  "Print Bill": "伝票印刷",
  "Print Report": "レポート印刷",
  "Preview Bill": "伝票プレビュー",
  "Printed": "印刷済み",
  "PRINTED": "印刷済み",
  "Not Printed": "未印刷",
  "NOT PRINTED": "未印刷",
  "Printed Status": "印刷状況",
  "Discard": "破棄",
  "Hide": "非表示",
  "Show": "表示",
  "Merge": "結合",
  "Split": "分割",
  "Modify": "変更",
  "Required": "必須",
  "Optional": "任意",
  "Optional remarks...": "任意の備考…",
  "None": "なし",
  "Not set": "未設定",
  "Not attached": "未添付",
  "N/A": "該当なし",
  "Active": "有効",
  "Inactive": "無効",
  "Enable": "有効化",
  "Disable": "無効化",
  "Include": "含む",
  "Among": "対象",
  "Status": "ステータス",
  "Action": "操作",
  "Actions": "操作",
  "Type": "種別",
  "Mode": "モード",
  "Module": "モジュール",
  "Value": "値",
  "Note": "メモ",
  "Notes": "メモ",
  "Remarks": "備考",
  "REMARKS": "備考",
  "Reason": "理由",
  "Description": "説明",
  "Date": "日付",
  "Time": "時刻",
  "Duration": "所要時間",
  "From": "開始",
  "To": "終了",
  "From Date": "開始日",
  "To Date": "終了日",
  "Start Date": "開始日",
  "End Date": "終了日",
  "Start Time": "開始時刻",
  "End Time": "終了時刻",
  "Search": "検索",
  "Search By": "検索方法",
  "Search items": "商品を検索",
  "Search Menu Items...": "メニューを検索…",
  "Search Orders...": "注文を検索…",
  "Search Table/Area...": "テーブル／エリアを検索…",
  "Search bill or ref": "伝票または参照番号を検索",
  "Search item…": "商品を検索…",
  "Search requisition, store...": "申請・店舗を検索…",
  "Barcode": "バーコード",
  "Search Menu Items / Scan Barcode...": "メニュー検索／バーコード読取…",
  "Search Orders / Barcode...": "注文・バーコードを検索…",
  "Search Table / Area / Barcode...": "テーブル／エリア／バーコードを検索…",
  "Search bill, ref or barcode": "伝票・参照番号・バーコードを検索",
  "Search name / barcode": "品名／バーコードを検索",
  "Search requisition, store, barcode...": "申請・店舗・バーコードを検索…",
  "Search item / barcode…": "商品／バーコードを検索…",
  "Search program / coupon / barcode…": "プログラム／クーポン／バーコードを検索…",
  "Search customer / card barcode…": "顧客／カードバーコードを検索…",
  "Search guest, hall, company, barcode…": "顧客・会場・会社・バーコードを検索…",
  "Search guest / company / reservation # / barcode": "顧客／会社／予約番号／バーコードを検索",
  "Search For Bill RePrint": "再印刷する伝票を検索",
  "Filters": "絞り込み",
  "Filter By": "絞り込み条件",
  "Filter Bills": "伝票を絞り込む",
  "Open Filters": "絞り込みを開く",
  "Presets": "プリセット",
  "Group By": "グループ化",
  "Summary": "サマリー",
  "SUMMARY": "サマリー",
  "Details": "詳細",
  "Ref": "参照",
  "S.No": "No.",
  "Size": "サイズ",
  "Small": "小",
  "Medium": "中",
  "Large": "大",
  "Short": "短い",
  "Regular": "通常",
  "Standard": "標準",
  "STANDARD": "標準",
  "Price": "価格",
  "Quantity": "数量",
  "Qty": "数量",
  "QTY": "数量",
  "Amount": "金額",
  "Total": "合計",
  "TOTAL": "合計",
  "Total Amount": "合計金額",
  "Subtotal": "小計",
  "Sub Total": "小計",
  "Grand Total": "総合計",
  "GRAND TOTAL": "合計金額",
  "Balance Due": "未払残高",
  "Balance Qty": "残数量",
  "Balance after": "処理後残高",
  "Balanced": "一致",
  "Difference": "差異",
  "Over": "超過",
  "Currency": "通貨",
  "Currency Symbol": "通貨記号",
  "Yes": "はい",
  "YES": "はい",
  "No": "いいえ",

  /* ---------------- Tables & order flow ---------------- */
  "Table": "テーブル",
  "TABLE": "テーブル",
  "Table / Take Away": "テーブル／テイクアウト",
  "Take Away": "テイクアウト",
  "Take Away Orders": "テイクアウト注文",
  "Takeaway": "テイクアウト",
  "Delivery": "デリバリー",
  "Dine In": "店内",
  "Dine-in": "店内",
  "Event": "イベント",
  "Available": "空席",
  "Available On": "利用可能日",
  "Occupied": "使用中",
  "Reserved": "予約済み",
  "Vacant": "空席",
  "In Use": "使用中",
  "Billed": "請求済み",
  "Completed": "完了",
  "Closed": "締め済み",
  "On Hold": "保留中",
  "Hold": "保留",
  "New": "新規",
  "New Order": "新規注文",
  "New Customer": "新規顧客",
  "Inventory Update": "在庫更新",
  "Place Order": "注文確定",
  "Pay Now": "支払う",
  "Billing": "会計",
  "Billing Info": "請求情報",
  "Orders On Hold": "保留中の注文",
  "Ordered": "注文済み",
  "Ordered Items": "注文済み商品",
  "View All Orders": "すべての注文",
  "View / Continue Order": "注文を表示／続行",
  "View / Take Order": "注文を表示／取得",
  "View / Edit": "表示／編集",
  "View Bill": "伝票を見る",
  "View bill": "伝票を見る",
  "All Categories": "すべてのカテゴリー",
  "ALL CATEGORIES": "すべてのカテゴリー",
  "ALL": "すべて",
  "All": "すべて",
  "All items": "すべての商品",
  "Categories": "カテゴリー",
  "CATEGORIES": "カテゴリー",
  "Item": "商品",
  "Items": "商品",
  "ITEMS": "商品",
  "Item Name": "商品名",
  "ITEM NAME": "商品名",
  "Item Group": "商品グループ",
  "ITEM GROUP": "商品グループ",
  "Item Details List": "商品明細一覧",
  "Product": "商品",
  "Products": "商品",
  "Product Tags": "商品タグ",
  "Specific Products": "特定の商品",
  "Cheapest Product": "最安の商品",
  "Free Product": "無料商品",
  "Cart is empty": "カートは空です",
  "Order Type": "注文タイプ",
  "Order Summary": "注文サマリー",
  "Order Ticket": "注文伝票",
  "Order On": "注文日時",
  "Other Info": "その他情報",
  "OTHER INFO": "その他情報",
  "General": "一般",
  "General Information": "基本情報",
  "Primary Information": "基本情報",
  "Guest": "お客様",
  "Guest Name": "お客様名",
  "Enter Guest Name": "お客様名を入力",
  "Enter guest name": "お客様名を入力",
  "Enter Total Cover": "客数を入力",
  "Enter company": "会社名を入力",
  "Choose Company": "会社を選択",
  "Company": "会社",
  "Guest / Company Details": "お客様／会社情報",
  "Guest Info": "お客様情報",
  "Guest Complaint": "お客様からの苦情",
  "Walk-in Guest": "ウォークイン客",
  "Room Guest": "宿泊客",
  "Room Number": "部屋番号",
  "VIP Guest": "VIP客",
  "VIP Room": "VIPルーム",
  "Contact Number": "連絡先番号",
  "Address": "住所",
  "Email": "メール",
  "Pax": "人数",
  "Total Pax": "合計人数",
  "Expected Pax": "予定人数",
  "Guaranteed Pax": "保証人数",
  "Rate / Pax": "単価／人",
  "Tax": "税",
  "Tax Collected": "預り消費税",
  "Tax Included": "税込",
  "Tax Excluded": "税抜",
  "Tax Exempt": "非課税",
  "Non Taxable": "非課税",
  "Taxable Amt": "課税額",
  "Vat Amt": "消費税額",
  "Tax Category Master": "税区分マスタ",
  "Tax Rule Master": "税ルールマスタ",
  "Standard Tax Item": "標準税率商品",
  "Reduced Tax Eligible": "軽減税率対象",
  "Consumption Tax": "消費税",
  "Consumption Tax (Reduced / Standard)": "消費税（軽減／標準）",
  "Non-Chargeable": "無料",
  "Charges & Advance": "料金・前受金",
  "Estimated Charge": "見込み料金",
  "Total Charge": "合計料金",
  "Hall Charge": "会場料金",
  "Advance": "前受金",
  "Advance Held": "預り前受金",
  "Advance Received": "受領前受金",
  "Tip": "チップ",
  "Tip (optional)": "チップ（任意）",
  "Please enter quantity.": "数量を入力してください。",
  "No items match your search.": "検索に一致する商品はありません。",
  "No items match this filter.": "この条件に一致する商品はありません。",
  "No items on this bill.": "この伝票に商品はありません。",
  "No orders match your search.": "検索に一致する注文はありません。",
  "No tables match your search.": "検索に一致するテーブルはありません。",
  "No bills match your filter.": "条件に一致する伝票はありません。",
  "No records for the selected filter.": "選択した条件のデータはありません。",
  "No reservations match your filters.": "条件に一致する予約はありません。",
  "No store requests match your filter.": "条件に一致する店舗申請はありません。",
  "You can perform Table related actions from here.": "ここからテーブル関連の操作ができます。",
  "Orders for take away are displayed here.": "テイクアウト注文はここに表示されます。",
  "Put bill on hold?": "伝票を保留にしますか？",

  /* ---------------- Modifiers / kitchen notes ---------------- */
  "Nan or Rice": "ナンまたはライス",
  "Plain naan": "プレーンナン",
  "Plain nan": "プレーンナン",
  "Garlic Naan": "ガーリックナン",
  "Garlic naan": "ガーリックナン",
  "Butter Naan": "バターナン",
  "Herb butter naan": "ハーブバターナン",
  "Basmati Rice": "バスマティライス",
  "BASMATI RICE": "バスマティライス",
  "Set drink": "セットドリンク",
  "Drink timing": "ドリンク提供時間",
  "Drinks": "ドリンク",
  "Drink": "ドリンク",
  "Before meals": "食前",
  "After meal": "食後",
  "Serve together": "一緒に提供",
  "Simultaneous": "同時提供",
  "Serving style": "提供スタイル",
  "As is": "そのまま",
  "On the rocks": "ロック",
  "Chilled": "冷たく",
  "Steamed": "蒸し",
  "Ice level": "氷の量",
  "No ice": "氷なし",
  "Less ice": "氷少なめ",
  "Normal ice": "氷普通",
  "Mild": "マイルド",
  "Medium spice": "中辛",
  "Extra spicy": "激辛",
  "No onion": "玉ねぎ抜き",
  "Add a snack": "スナックを追加",
  "After-dinner ice cream": "食後のアイスクリーム",
  "Mixed nuts": "ミックスナッツ",
  "Ginger ale": "ジンジャーエール",
  "Orange juice": "オレンジジュース",
  "Mango lassi": "マンゴーラッシー",
  "Oolong tea": "ウーロン茶",
  "Ladies' set": "レディースセット",
  "Vegetarian menu for 12 guests.": "12名様向けベジタリアンメニュー。",
  "Alcohol": "アルコール",
  "Beverages": "飲料",
  "Food": "フード",
  "Dessert": "デザート",
  "Soup": "スープ",
  "Sushi": "寿司",
  "Ramen": "ラーメン",
  "Merchandise": "物販",
  "Grocery": "食料品",
  "GROCERY": "食料品",
  "DAIRY": "乳製品",
  "Meat & Poultry": "食肉・鶏肉",
  "MEAT & POULTRY": "食肉・鶏肉",
  "Coffee Supplies": "コーヒー用品",
  "Coffee supplies": "コーヒー用品",
  "Purchased coffee beans": "コーヒー豆の仕入れ",
  "Staff Lunch": "スタッフ賄い",
  "Staff lunch": "スタッフ賄い",
  "Lunch for kitchen staff": "厨房スタッフの賄い",

  /* ---------------- Payments & settlement ---------------- */
  "Cash": "現金",
  "Card": "カード",
  "Credit": "掛売",
  "Cheque": "小切手",
  "Bank Transfer": "銀行振込",
  "E-Wallet": "電子ウォレット",
  "QR Payment": "QR決済",
  "QR Payments": "QR決済",
  "QR / e-Money": "QR／電子マネー",
  "Voucher": "バウチャー",
  "Voucher Number Name": "バウチャー番号／名称",
  "Gift": "ギフト",
  "Restaurant Gift Card": "レストランギフトカード",
  "Payment Mode": "支払方法",
  "Select a payment mode": "支払方法を選択",
  "Selected mode": "選択中の支払方法",
  "Split Payments": "分割支払い",
  "Settle": "精算",
  "Settled": "精算済み",
  "SETTLED": "精算済み",
  "Settle Now": "今すぐ精算",
  "Settle Bill": "会計する",
  "Settle & Print": "精算して印刷",
  "Settlement Details": "精算明細",
  "Settlement List": "精算一覧",
  "Settlement Of": "精算対象",
  "Settlement Receipt": "精算レシート",
  "Settlement Summary": "精算サマリー",
  "Bill Amount": "請求金額",
  "Bill List": "伝票一覧",
  "Bill Of": "伝票対象",
  "Bill Summary": "伝票サマリー",
  "RePrint": "再印刷",
  "RePrint Bill": "伝票を再印刷",
  "Reprint Of": "再印刷対象",
  "REGENERATE BILL": "伝票を再生成",
  "Invoice": "請求書",
  "Transaction Date": "取引日",
  "TRANSACTION DATE": "取引日",
  "Transaction History": "取引履歴",

  /* ---------------- Shift / cash ---------------- */
  "Shift Overview": "シフト概要",
  "Shift Information": "シフト情報",
  "Shift Type": "シフト種別",
  "Shift Close": "シフト締め",
  "Shift Close Report": "シフト締めレポート",
  "Shift Closed": "シフト締め済み",
  "Start New Shift": "新しいシフトを開始",
  "New Shift": "新規シフト",
  "Open Shift": "シフト開始",
  "Close Shift": "シフト締め",
  "Morning": "午前",
  "Morning Shift": "早番",
  "Morning Shift Close": "早番の締め",
  "Morning busy hours": "午前の繁忙時間",
  "Evening Shift": "遅番",
  "Opening Cash": "開始現金",
  "Opening Float": "釣銭準備金",
  "Opening Note": "開始メモ",
  "Opening cash added": "開始現金を登録しました",
  "Opening (reference only)": "開始（参考値）",
  "Initial cash for opening": "開始時の準備現金",
  "Closing Note": "締めメモ",
  "Closing Reconciliation": "締め時の照合",
  "Closing receipt with reconciliation": "照合付きの締めレシート",
  "Closed By": "締め担当",
  "Closed On": "締め日時",
  "Expected Cash": "理論現金",
  "Expected Closing": "理論締め金額",
  "Counted Cash": "実査現金",
  "Total Counted Cash": "実査現金合計",
  "Count Cash": "現金を数える",
  "Count each denomination to calculate total": "金種ごとに数えて合計を算出します",
  "Cash Breakdown": "現金内訳",
  "Cash In": "入金",
  "Cash Out": "出金",
  "Cash In / Out": "入出金",
  "Cash In / Cash Out History": "入出金履歴",
  "Cash Out (Expenses)": "出金（経費）",
  "Cash Movement Summary": "現金移動サマリー",
  "Total Cash In": "入金合計",
  "Total Cash Out": "出金合計",
  "Add Cash In": "入金を追加",
  "Edit Cash In": "入金を編集",
  "Add Expense": "経費を追加",
  "Edit Expense": "経費を編集",
  "Additional cash from sales": "売上からの追加現金",
  "Current Cash Balance": "現在の現金残高",
  "Current Balance": "現在残高",
  "Current balance": "現在残高",
  "Denomination": "金種",
  "Denomination Summary (Counted Cash)": "金種別サマリー（実査現金）",
  "Coins": "硬貨",
  "Reconciliation Summary": "照合サマリー",
  "All good and ready to start the day.": "問題なし。営業開始の準備ができています。",
  "All sales recorded and cash verified.": "売上を記録し、現金を確認しました。",
  "Editing entry": "エントリーを編集中",

  /* ---------------- Promotions & loyalty ---------------- */
  "Discount": "割引",
  "Discounts": "割引",
  "Discount %": "割引率",
  "Discount Amount": "割引額",
  "DISCOUNT TYPE": "割引タイプ",
  "Discount & Loyalty": "割引・ポイント",
  "Discounts & Loyalty": "割引・ポイント",
  "Maximum Discount": "最大割引額",
  "MAXIMUM DISCOUNT AMOUNT": "最大割引額",
  "FIXED AMOUNT": "定額",
  "Loyalty": "ポイント",
  "Loyalty Program": "ポイントプログラム",
  "Loyalty Program Settings": "ポイントプログラム設定",
  "Loyalty Earning": "ポイント付与",
  "Points": "ポイント",
  "Point value": "ポイント単価",
  "Min. redemption": "最低交換ポイント",
  "Earned": "獲得",
  "Redeem": "利用する",
  "Redeemed": "利用済み",
  "Coupon": "クーポン",
  "Coupons": "クーポン",
  "Coupon Code": "クーポンコード",
  "Coupon Expired": "クーポンの有効期限切れ",
  "Coupon Already Used": "このクーポンは使用済みです",
  "Invalid Coupon": "無効なクーポン",
  "Generate": "生成",
  "Generate Coupons": "クーポンを生成",
  "Generated By": "生成者",
  "Generated On": "生成日",
  "Auto Generated": "自動生成",
  "Used": "使用済み",
  "USED": "使用済み",
  "Unused": "未使用",
  "NOT USED": "未使用",
  "PARTIALLY USED": "一部使用",
  "PURGED": "削除済み",
  "Is Used": "使用済みか",
  "Is Purged": "削除済みか",
  "Limit Usage": "使用回数制限",
  "Valid Until": "有効期限",
  "Expired": "期限切れ",
  "Program Name": "プログラム名",
  "Program Type": "プログラム種別",
  "Programs": "プログラム",
  "New Program": "新規プログラム",
  "Edit Program": "プログラムを編集",
  "Rules & Rewards": "ルールと特典",
  "Conditional Rule": "条件付きルール",
  "Conditional Rules": "条件付きルール",
  "Reward": "特典",
  "Rewards": "特典",
  "Reward Type": "特典タイプ",
  "Minimum Purchase": "最低購入金額",
  "Minimum Quantity": "最低数量",
  "Applies To": "適用対象",
  "Available Promotions": "利用可能なプロモーション",
  "Promotion Usage History": "プロモーション利用履歴",
  "No active promotions.": "有効なプロモーションはありません。",
  "No promotions used yet.": "まだプロモーションの利用はありません。",
  "No coupons generated for this program yet.": "このプログラムのクーポンはまだ生成されていません。",
  "No rewards configured yet.": "特典はまだ設定されていません。",
  "Promotions, coupons and the loyalty points program.": "プロモーション、クーポン、ポイントプログラム。",
  "Student Discount": "学割",
  "Student ID required": "学生証が必要です",
  "Students": "学生",
  "Happy Hour": "ハッピーアワー",
  "Birthday Coupon": "誕生日クーポン",
  "Birthday treat": "誕生日特典",
  "Weekend special": "週末限定",
  "Cashback": "キャッシュバック",
  "Cashback Amount": "キャッシュバック額",
  "Recent partners": "最近の取引先",
  "Recent servers": "最近の担当者",
  "Guest server": "担当スタッフ",
  "Approval Level": "承認レベル",
  "Approved By": "承認者",
  "Approved On": "承認日",
  "APPROVED DATE": "承認日",
  "Acknowledge By": "確認者",
  "Acknowledge On": "確認日",

  /* ---------------- Events ---------------- */
  "Event Booking": "イベント予約",
  "Event Date": "イベント日",
  "Event From": "イベント開始",
  "Event To": "イベント終了",
  "Event Reservation Report": "イベント予約レポート",
  "Event reservation saved": "イベント予約を保存しました",
  "Reservations": "予約",
  "All Reservations": "すべての予約",
  "Booking Details": "予約詳細",
  "Booking Status": "予約ステータス",
  "Hall": "ホール",
  "Hall / Venue": "ホール／会場",
  "Hall / Table Availability": "ホール／テーブル空き状況",
  "No of Halls": "ホール数",
  "Halls": "ホール",
  "Function": "催事",
  "Function Type": "催事種別",
  "Conference": "会議",
  "Seminar": "セミナー",
  "Wedding": "結婚式",
  "Birthday Party": "誕生日パーティー",
  "Corporate Meeting": "企業ミーティング",
  "Family Gathering": "家族の集まり",
  "Tentative": "仮予約",
  "Sales Executive": "営業担当",
  "Fiscal Year": "会計年度",
  "Financials": "金額情報",
  "Basic Info": "基本情報",
  "Basic Info-Group": "基本情報グループ",
  "Green blocks show the slot held by this booking.": "緑のブロックはこの予約が押さえている時間帯です。",
  "Setup, menu or seating notes": "設営・メニュー・席次のメモ",
  "Rooftop": "ルーフトップ",
  "Load Report": "レポートを読み込む",
  "No report loaded yet": "レポートは未読み込みです",
  "Report By": "レポート区分",
  "Tap a row to view the full report": "行をタップすると全体を表示します",

  /* ---------------- Store request / inventory ---------------- */
  "Store Request Report": "店舗申請レポート",
  "Filter - Store Request Report": "絞り込み - 店舗申請レポート",
  "New Store Request": "新規店舗申請",
  "New Request": "新規申請",
  "Submit Request": "申請を送信",
  "Requested By": "申請者",
  "REQUESTED BY": "申請者",
  "Requested Qty": "申請数量",
  "Issued Qty": "出庫数量",
  "Requisition Date": "申請日",
  "Required Date": "必要日",
  "Req By Cost Center": "コストセンター別申請",
  "Req By Sub Store": "サブストア別申請",
  "Store": "店舗",
  "STORE": "店舗",
  "Store Type": "店舗種別",
  "Store/Sub Store": "店舗／サブストア",
  "STORE/SUB STORE": "店舗／サブストア",
  "SUB STORE": "サブストア",
  "Sub-Store/Cost Center": "サブストア／コストセンター",
  "Current Stock": "現在庫",
  "UOM": "単位",
  "Packet": "パック",
  "PACKET": "パック",
  "BOTTLE": "ボトル",
  "PAN": "パン",
  "Browse and track store requisitions.": "店舗申請の一覧と進捗を確認します。",
  "Raise a new store requisition and add items to it.": "新しい店舗申請を作成し、商品を追加します。",
  "Set your filters and load the Store Request report.": "条件を設定して店舗申請レポートを読み込みます。",
  "Select item...": "商品を選択…",
  "No limit": "上限なし",

  /* ---------------- Customer ordering / QR ---------------- */
  "Restaurant Identity": "店舗情報",
  "Shown on the guest ordering page": "お客様の注文ページに表示されます",
  "Ordering Base URL": "注文ページのベースURL",
  "Ordering Rules": "注文ルール",
  "How guest orders reach the kitchen": "お客様の注文がキッチンに届く流れ",
  "Default Language": "既定の言語",
  "Show in QR ordering": "QR注文に表示する",
  "Publish the live menu to guest phones": "お客様のスマホに最新メニューを公開",
  "Large touch allergen badges": "大きなアレルゲンバッジ",
  "Big icons for allergens on guest menu": "お客様メニューにアレルゲンを大きく表示",
  "Require staff confirmation": "スタッフの承認を必須にする",
  "Guest orders wait for approval before KOT": "お客様の注文は承認後にKOTを発行",
  "Show prices with tax": "税込価格を表示",
  "Display tax-inclusive prices to guests": "お客様に税込価格を表示します",
  "Enable Call Waiter button": "スタッフ呼び出しボタンを有効化",
  "Guest can ping the floor from their phone": "お客様がスマホからスタッフを呼べます",
  "Menu Setup — Multi-language Matrix": "メニュー設定 — 多言語マトリクス",
  "One row per item, one column per guest language. Allergen badges show on the guest menu.": "1行1商品、1列1言語。アレルゲンバッジはお客様メニューに表示されます。",
  "Allergens": "アレルゲン",
  "Egg": "卵",
  "Milk": "乳",
  "Wheat": "小麦",
  "Shrimp": "えび",
  "Soy": "大豆",
  "Fish": "魚",
  "QR Code Generator": "QRコード生成",
  "QR Generator": "QR生成",
  "Every table gets a signed dynamic token. Regenerate to invalidate old codes.": "各テーブルに署名付きトークンを発行。再生成すると旧コードは無効になります。",
  "Regenerate All": "すべて再生成",
  "Print All Table QRs": "全テーブルのQRを印刷",
  "Tent card preview": "卓上POPプレビュー",
  "Token Preview": "トークンのプレビュー",
  "Copy ordering link": "注文リンクをコピー",
  "Link copied": "リンクをコピーしました",
  "Scan to view menu & order": "スキャンしてメニューを見る・注文する",
  "Mobile Theme": "モバイルテーマ",
  "Applied to the guest ordering page on every table QR": "各テーブルQRのお客様注文ページに適用されます",
  "Guest language switcher": "お客様の言語切替",
  "Orders are confirmed by staff before cooking": "調理前にスタッフが注文を確認します",
  "Sakura": "桜",
  "Matcha": "抹茶",
  "Indigo": "藍",
  "Charcoal": "墨",
  "Salmon Sushi": "サーモン寿司",
  "Shoyu Ramen": "醤油ラーメン",
  "Miso Soup": "味噌汁",
  "Green Tea": "緑茶",
  "Ebi Tempura": "海老天ぷら",
  "Matcha Cake": "抹茶ケーキ",
  "Allergen data is printed on the KOT and shown as large badges on the guest phone.": "アレルゲン情報はKOTに印字され、お客様のスマホに大きく表示されます。",

  /* ---------------- Settings ---------------- */
  "Outlet-wide configuration for this POS terminal.": "このPOS端末の店舗全体設定。",
  "License Info": "ライセンス情報",
  "Change Name": "名称を変更",
  "Color Me": "テーマカラー",
  "TARGET MENU": "対象メニュー",
  "REASON CHIPS": "定型理由",
  "LEVEL 1": "レベル1",


  /* ---------------- Menu items & misc dynamic labels ---------------- */
  "Chicken Tikka": "チキンティッカ",
  "Butter Chicken": "バターチキン",
  "Paneer Tikka": "パニールティッカ",
  "Chicken Katsu Don": "チキンカツ丼",
  "Teriyaki Chicken Don": "照り焼きチキン丼",
  "Salmon Bento": "サーモン弁当",
  "Salmon Bento Box": "サーモン弁当",
  "Salmon Sushi Set": "サーモン寿司セット",
  "Edamame": "枝豆",
  "Momo": "モモ",
  "Coke": "コーラ",
  "Cola": "コーラ",
  "Coca-Cola 500ml": "コカ・コーラ 500ml",
  "Draft Beer 500ml": "生ビール 500ml",
  "Hot Sake 180ml": "熱燗 180ml",
  "House Wine Glass": "ハウスワイン（グラス）",
  "Oolong Tea Bottle": "ウーロン茶（ボトル）",
  "Lassi": "ラッシー",
  "House original dressing": "自家製ドレッシング",
  "Chicken Breast": "鶏むね肉",
  "CHICKEN BREAST": "鶏むね肉",
  "MOZZARELLA CHEESE": "モッツァレラチーズ",
  "items are running low in stock": "商品の在庫が少なくなっています",
  "orders delayed in kitchen": "件の注文がキッチンで遅延しています",
  "of total": "（全体に対する割合）",
  "Uber Eats": "ウーバーイーツ",
  "PENDING": "保留中",
  "ORDER": "注文",
  "OUTLET": "店舗",
  "BILL": "伝票",
  "BAR": "バー",
  "PATIO": "テラス",
  "MAIN HALL": "メインホール",
  "MAIN KITCHEN": "メインキッチン",
  "HOUSEKEEPING": "ハウスキーピング",
  "NEED": "必要",
  "Wedding": "結婚式",

  /* ---------------- Days ---------------- */
  "Mon": "月",
  "Tue": "火",
  "Wed": "水",
  "Thu": "木",
  "Fri": "金",
  "Sat": "土",
  "Sun": "日",
  "Wednesday": "水曜日",
};

export default JA_DICT;
